### ISSUE TITLE
Can't install on Windows Server 2012 R2

### ISSUE THREAD

**Issue by Detsle** [abbodi1406/dotNetFx35W10#1]
Good afternoon, earlier, your installer helped to cope with the installation problem on the Windows Server. Now when I launch new versions, he says that this is only for Windows 10.
Perhaps somehow ask you to upload a file for Windows Server 2012 R2?

**Comment by abbodi1406** [comment]
inno setup release
http://www.solidfiles.com/d/ZMQXKpPQ7p7Qg
http://www.mediafire.com/download/sqnnpirtzcj8ka1/dotNetFx35_W8.1_x86_x64_2017.exe

7zsfx release
https://1drv.ms/u/s!AhOEoZ7nJmxFgUhRDSSmY2ExUh1i
